# Generated by Django 5.1.5 on 2025-09-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.FloatField()),
                ('reviews', models.PositiveIntegerField()),
                ('is_new', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('is_customizable', models.BooleanField(default=False)),
                ('customization_options', models.JSONField(blank=True, default=list, null=True)),
                ('show_on_home', models.BooleanField(default=False)),
                ('show_on_products', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], max_length=8)),
            ],
        ),
    ]
