# Generated by Django 5.1.5 on 2025-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('categoryId', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('originalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.FloatField()),
                ('reviews', models.PositiveIntegerField()),
                ('isNew', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=False, max_length=10)),
                ('isSale', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=False, max_length=10)),
                ('description', models.TextField()),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('isCustomizable', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=False, max_length=10)),
                ('customizationOptions', models.JSONField(blank=True, default=list, null=True)),
                ('showOnHome', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=False, max_length=10)),
                ('showOnProducts', models.CharField(choices=[('true', 'True'), ('false', 'False')], default=False, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], max_length=8)),
            ],
        ),
    ]
