# Generated by Django 5.1.5 on 2025-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_customizable',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_sale',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_on_home',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_on_products',
            field=models.BooleanField(choices=[('true', 'True'), ('false', 'False')], default=False),
        ),
    ]
