# Generated by Django 5.1.5 on 2025-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_is_customizable_alter_products_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_customizable',
            field=models.BooleanField(choices=[('True', 'true'), ('False', 'false')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(choices=[('True', 'true'), ('False', 'false')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_sale',
            field=models.BooleanField(choices=[('True', 'true'), ('False', 'false')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_on_home',
            field=models.BooleanField(choices=[('True', 'true'), ('False', 'false')], default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_on_products',
            field=models.BooleanField(choices=[('True', 'true'), ('False', 'false')], default=False),
        ),
    ]
