# Generated by Django 5.1.5 on 2025-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
